name: unofficial_twitch_open_api
description: Wrapper for the newest Twitch API. It returns informations about channels, media, search and game
version: 0.0.1
homepage: https://www.federicoviceconti.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  unofficial_twitch_http: ^0.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: