enum LoginScope {
  openId,
  analyticsReadExtensions,
  analyticsReadGames,
  bitsRead,
  channelEditCommercial,
  channelManageBroadcast,
  channelManageExtensions,
  channelManagePolls,
  channelManagePredictions,
  channelManageRedemptions,
  channelManageSchedule,
  channelManageVideos,
  channelReadEditors,
  channelReadGoals,
  channelReadHypeTrain,
  channelReadPolls,
  channelReadPredictions,
  channelReadRedemptions,
  channelReadStreamKey,
  channelReadSubscriptions,
  clipsEdit,
  moderationRead,
  moderatorManageBannedUsers,
  moderatorReadBlockedTerms,
  moderatorManageBlockedTerms,
  moderatorManageAutomod,
  moderatorReadAutomodSettings,
  moderatorManageAutomodSettings,
  moderatorReadChatSettings,
  moderatorManageChatSettings,
  userEdit,
  userEditFollows,
  userManageBlockedUsers,
  userReadBlockedUsers,
  userReadBroadcast,
  userReadEmail,
  userReadFollows,
  userReadSubscriptions,
}

extension LoginScopeExt on LoginScope {
  String get name => {
    LoginScope.openId: 'openid',
    LoginScope.analyticsReadExtensions: 'analytics:read:extensions',
    LoginScope.analyticsReadGames: 'analytics:read:games',
    LoginScope.bitsRead: 'bits:read',
    LoginScope.channelEditCommercial: 'channel:edit:commercial',
    LoginScope.channelManageBroadcast: 'channel:manage:broadcast',
    LoginScope.channelManageExtensions: 'channel:manage:extensions',
    LoginScope.channelManagePolls: 'channel:manage:polls',
    LoginScope.channelManagePredictions: 'channel:manage:predictions',
    LoginScope.channelManageRedemptions: 'channel:manage:redemptions',
    LoginScope.channelManageSchedule: 'channel:manage:schedule',
    LoginScope.channelManageVideos: 'channel:manage:videos',
    LoginScope.channelReadEditors: 'channel:read:editors',
    LoginScope.channelReadGoals: 'channel:read:goals',
    LoginScope.channelReadHypeTrain: 'channel:read:hype_train',
    LoginScope.channelReadPolls: 'channel:read:polls',
    LoginScope.channelReadPredictions: 'channel:read:predictions',
    LoginScope.channelReadRedemptions: 'channel:read:redemptions',
    LoginScope.channelReadStreamKey: 'channel:read:stream_key',
    LoginScope.channelReadSubscriptions: 'channel:read:subscriptions',
    LoginScope.clipsEdit: 'clips:edit',
    LoginScope.moderationRead: 'moderation:read',
    LoginScope.moderatorManageBannedUsers: 'moderator:manage:banned_users',
    LoginScope.moderatorReadBlockedTerms: 'moderator:read:blocked_terms',
    LoginScope.moderatorManageBlockedTerms: 'moderator:manage:blocked_terms',
    LoginScope.moderatorManageAutomod: 'moderator:manage:automod',
    LoginScope.moderatorReadAutomodSettings: 'moderator:read:automod_settings',
    LoginScope.moderatorManageAutomodSettings: 'moderator:manage:automod_settings',
    LoginScope.moderatorReadChatSettings: 'moderator:read:chat_settings',
    LoginScope.moderatorManageChatSettings: 'moderator:manage:chat_settings',
    LoginScope.userEdit: 'user:edit',
    LoginScope.userEditFollows: 'user:edit:follows',
    LoginScope.userManageBlockedUsers: 'user:manage:blocked_users',
    LoginScope.userReadBlockedUsers: 'user:read:blocked_users',
    LoginScope.userReadBroadcast: 'user:read:broadcast',
    LoginScope.userReadEmail: 'user:read:email',
    LoginScope.userReadFollows: 'user:read:follows',
    LoginScope.userReadSubscriptions: 'user:read:subscriptions',
  }[this]!;
}

extension LoginScopeStringExt on String {
  LoginScope get type => {
    'open_id': LoginScope.openId,
    'analytics:read:extensions': LoginScope.analyticsReadExtensions,
    'analytics:read:games': LoginScope.analyticsReadGames,
    'bits:read': LoginScope.bitsRead,
    'channel:edit:commercial': LoginScope.channelEditCommercial,
    'channel:manage:broadcast': LoginScope.channelManageBroadcast,
    'channel:manage:extensions': LoginScope.channelManageExtensions,
    'channel:manage:polls': LoginScope.channelManagePolls,
    'channel:manage:predictions': LoginScope.channelManagePredictions,
    'channel:manage:redemptions': LoginScope.channelManageRedemptions,
    'channel:manage:schedule': LoginScope.channelManageSchedule,
    'channel:manage:videos': LoginScope.channelManageVideos,
    'channel:read:editors': LoginScope.channelReadEditors,
    'channel:read:goals': LoginScope.channelReadGoals,
    'channel:read:hype_train': LoginScope.channelReadHypeTrain,
    'channel:read:polls': LoginScope.channelReadPolls,
    'channel:read:predictions': LoginScope.channelReadPredictions,
    'channel:read:redemptions': LoginScope.channelReadRedemptions,
    'channel:read:stream_key': LoginScope.channelReadStreamKey,
    'channel:read:subscriptions': LoginScope.channelReadSubscriptions,
    'clips:edit': LoginScope.clipsEdit,
    'moderation:read': LoginScope.moderationRead,
    'moderator:manage:banned_users': LoginScope.moderatorManageBannedUsers,
    'moderator:read:blocked_terms': LoginScope.moderatorReadBlockedTerms,
    'moderator:manage:blocked_terms': LoginScope.moderatorManageBlockedTerms,
    'moderator:manage:automod': LoginScope.moderatorManageAutomod,
    'moderator:read:automod_settings': LoginScope.moderatorReadAutomodSettings,
    'moderator:manage:automod_settings': LoginScope.moderatorManageAutomodSettings,
    'moderator:read:chat_settings': LoginScope.moderatorReadChatSettings,
    'moderator:manage:chat_settings': LoginScope.moderatorManageChatSettings,
    'user:edit': LoginScope.userEdit,
    'user:edit:follows': LoginScope.userEditFollows,
    'user:manage:blocked_users': LoginScope.userManageBlockedUsers,
    'user:read:blocked_users': LoginScope.userReadBlockedUsers,
    'user:read:broadcast': LoginScope.userReadBroadcast,
    'user:read:email': LoginScope.userReadEmail,
    'user:read:follows': LoginScope.userReadFollows,
    'user:read:subscriptions': LoginScope.userReadSubscriptions,
  }[this]!;
}